# Testing each method works for the Pipeline 

In [1]:
from functions import *
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# QUANT

## Static Quant (decrepacated)

In [3]:
from QGAP.Quant_Static import StaticQuantClassifier as SQC
sqc = SQC()

In [4]:
data_to_proximities(sqc, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[ 7,  1,  5, ...,  2,  6,  5],
       [ 7,  3,  5, ...,  2,  6,  5],
       [ 1,  4,  2, ...,  5, 12,  2],
       ...,
       [ 7,  3,  5, ...,  2,  6,  5],
       [ 1,  4,  2, ...,  5, 12,  6],
       [ 7,  1,  5, ...,  4,  6,  5]])

## RF-GAP QUANT

In [5]:
from QGAP.qgap import QGAP
qgap = QGAP(matrix_type="dense")

In [6]:
data_to_proximities(qgap, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[0.        , 0.04537539, 0.        , ..., 0.07058843, 0.        ,
        0.02944132],
       [0.04935792, 0.        , 0.        , ..., 0.03274878, 0.        ,
        0.0248325 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.09025484,
        0.        ],
       ...,
       [0.05344599, 0.05312502, 0.        , ..., 0.        , 0.        ,
        0.02492485],
       [0.        , 0.        , 0.07639586, ..., 0.        , 0.        ,
        0.        ],
       [0.03511017, 0.03177884, 0.        , ..., 0.02503912, 0.        ,
        0.        ]])

# REDCOMMET

In [ ]:
from Redcomets.Redcomets import REDCOMETS
redcomets = REDCOMETS(variant = 3, static = XSTATIC)
data_to_proximities(redcomets, XTRAIN, YTRAIN, XTEST, None , None)

# RF-GAP Rocket

In [ ]:
from RFGAP_Rocket.RFGAP_Rocket import RFGAP_Rocket

rf_rocket = RFGAP_Rocket(prediction_type = "classification", rocket = "Multi",
                         n_kernels=512) # Rocket Kwargs
data_to_proximities(rf_rocket, XTRAIN, YTRAIN, XTEST, XSTATIC , XSTATIC_TEST)

matrix([[0.        , 0.02910557, 0.        , ..., 0.04036683, 0.        ,
         0.03197077],
        [0.03026345, 0.        , 0.00241546, ..., 0.03103207, 0.00198413,
         0.03738857],
        [0.00453216, 0.00405556, 0.        , ..., 0.00659649, 0.04573167,
         0.00811111],
        ...,
        [0.03016046, 0.02554285, 0.00565574, ..., 0.        , 0.03115741,
         0.03569199],
        [0.0046527 , 0.00460584, 0.04918084, ..., 0.00325413, 0.        ,
         0.00860778],
        [0.03062193, 0.03644385, 0.        , ..., 0.03932799, 0.00086806,
         0.        ]])

# RDST 

In [ ]:
from RDST.rdst import RDST_GAP

rdst = RDST_GAP(save_transformed_data = True)
prox = data_to_proximities(rdst, XTRAIN, YTRAIN, None, XSTATIC , None)
prox