# Testing each method works for the Pipeline 

In [1]:
from functions import *
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# QUANT

## Static Quant (decrepacated)

In [3]:
from QGAP.Quant_Static import StaticQuantClassifier as SQC
sqc = SQC()

In [4]:
data_to_proximities(sqc, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[11,  2,  2, ...,  5,  6,  5],
       [11,  2,  2, ...,  5,  4,  5],
       [ 2,  4,  5, ...,  2,  5,  3],
       ...,
       [11,  5,  2, ...,  5,  6,  5],
       [ 2,  4,  5, ...,  2,  5,  3],
       [11,  2,  2, ...,  5,  1,  5]])

## RF-GAP QUANT

In [5]:
from QGAP.qgap import QGAP
qgap = QGAP(matrix_type="dense")

In [6]:
data_to_proximities(qgap, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[0.        , 0.03552742, 0.        , ..., 0.04465181, 0.        ,
        0.03456962],
       [0.03343184, 0.        , 0.        , ..., 0.05301502, 0.        ,
        0.02680318],
       [0.        , 0.        , 0.        , ..., 0.        , 0.06021138,
        0.        ],
       ...,
       [0.04678223, 0.04819252, 0.        , ..., 0.        , 0.        ,
        0.02515337],
       [0.        , 0.        , 0.08776773, ..., 0.        , 0.        ,
        0.        ],
       [0.02772664, 0.02853524, 0.        , ..., 0.02119901, 0.        ,
        0.        ]])

# REDCOMMET

In [7]:
from Redcomets.Redcomets import REDCOMETS
redcomets = REDCOMETS(variant = 3, static = XSTATIC)
data_to_proximities(redcomets, XTRAIN, YTRAIN, XTEST, None , None)

array([[1.        , 0.32712015, 0.1316834 , ..., 0.29409137, 0.12875   ,
        0.18998829],
       [0.32712015, 1.        , 0.12107095, ..., 0.40786647, 0.14758534,
        0.23338186],
       [0.1316834 , 0.12107095, 1.        , ..., 0.19747323, 0.3438504 ,
        0.12389224],
       ...,
       [0.29409137, 0.40786647, 0.19747323, ..., 1.        , 0.13106091,
        0.18790161],
       [0.12875   , 0.14758534, 0.3438504 , ..., 0.13106091, 1.        ,
        0.07781124],
       [0.18998829, 0.23338186, 0.12389224, ..., 0.18790161, 0.07781124,
        1.        ]])