# Testing each method works for the Pipeline 

In [1]:
from functions import *
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# QUANT

In [3]:
from QGAP.Quant_Static import StaticQuantClassifier as SQC
sqc = SQC()

In [4]:
data_to_proximities(sqc, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[3, 4, 8, ..., 1, 8, 2],
       [3, 7, 8, ..., 6, 8, 8],
       [6, 3, 3, ..., 4, 5, 5],
       ...,
       [3, 4, 8, ..., 5, 8, 4],
       [6, 8, 3, ..., 4, 5, 5],
       [8, 5, 8, ..., 1, 1, 2]])

# RF-GAP QUANT

In [5]:
from QGAP.qgap import QGAP
qgap = QGAP(matrix_type="dense")

In [6]:
data_to_proximities(qgap, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[0.        , 0.04144167, 0.        , ..., 0.05689936, 0.        ,
        0.0269853 ],
       [0.03935934, 0.        , 0.        , ..., 0.05088562, 0.        ,
        0.02516734],
       [0.        , 0.        , 0.        , ..., 0.        , 0.07127952,
        0.        ],
       ...,
       [0.04242138, 0.04347364, 0.        , ..., 0.        , 0.        ,
        0.0203085 ],
       [0.        , 0.        , 0.07233415, ..., 0.        , 0.        ,
        0.        ],
       [0.02416164, 0.02743681, 0.        , ..., 0.01670961, 0.        ,
        0.        ]])

# REDCOMMET

In [ ]:
from Redcomets.Redcomets import REDCOMETS
redcomets = REDCOMETS(variant = 3, static = XSTATIC)
data_to_proximities(redcomets, XTRAIN, YTRAIN, XTEST, None , None)

array([[1.        , 0.35707686, 0.1036889 , ..., 0.3051215 , 0.0561345 ,
        0.1186126 ],
       [0.35707686, 1.        , 0.08797259, ..., 0.46493925, 0.11494066,
        0.16531647],
       [0.1036889 , 0.08797259, 1.        , ..., 0.16241311, 0.34744843,
        0.05153009],
       ...,
       [0.3051215 , 0.46493925, 0.16241311, ..., 1.        , 0.11593247,
        0.08670811],
       [0.0561345 , 0.11494066, 0.34744843, ..., 0.11593247, 1.        ,
        0.04772676],
       [0.1186126 , 0.16531647, 0.05153009, ..., 0.08670811, 0.04772676,
        1.        ]])