# Testing each method works for the Pipeline 

In [2]:
from functions import *
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [3]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


In [12]:
XTRAIN.shape

(50, 1, 150)

# QUANT

## Static Quant (decrepacated)

In [3]:
from QGAP.Quant_Static import StaticQuantClassifier as SQC
sqc = SQC()

In [4]:
data_to_proximities(sqc, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[6, 5, 6, ..., 2, 5, 5],
       [3, 5, 6, ..., 8, 5, 8],
       [5, 2, 5, ..., 5, 3, 3],
       ...,
       [3, 3, 6, ..., 2, 5, 5],
       [5, 2, 3, ..., 5, 3, 3],
       [6, 5, 7, ..., 2, 1, 8]])

## RF-GAP QUANT

In [5]:
from QGAP.qgap import QGAP
qgap = QGAP(matrix_type="dense")

In [6]:
data_to_proximities(qgap, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[0.        , 0.04522466, 0.        , ..., 0.03183484, 0.        ,
        0.03754225],
       [0.04955102, 0.        , 0.        , ..., 0.05302969, 0.        ,
        0.03246651],
       [0.        , 0.        , 0.        , ..., 0.        , 0.06238728,
        0.        ],
       ...,
       [0.04299305, 0.05658372, 0.        , ..., 0.        , 0.        ,
        0.02090186],
       [0.        , 0.        , 0.07705411, ..., 0.        , 0.        ,
        0.        ],
       [0.03339484, 0.03390755, 0.        , ..., 0.02380139, 0.        ,
        0.        ]])

# REDCOMMET

In [7]:
from Redcomets.Redcomets import REDCOMETS
redcomets = REDCOMETS(variant = 3, static = XSTATIC)
data_to_proximities(redcomets, XTRAIN, YTRAIN, XTEST, None , None)

array([[0.        , 0.03207379, 0.01831591, ..., 0.0342522 , 0.01064918,
        0.01122511],
       [0.03220306, 0.        , 0.01844516, ..., 0.0536128 , 0.02334289,
        0.01678643],
       [0.02390911, 0.01925418, 0.        , ..., 0.02993214, 0.03203162,
        0.00958939],
       ...,
       [0.02738665, 0.04561709, 0.03814092, ..., 0.        , 0.02052237,
        0.00797935],
       [0.01459555, 0.02041741, 0.02671513, ..., 0.02828859, 0.        ,
        0.00643794],
       [0.01637853, 0.01457329, 0.01619505, ..., 0.01063539, 0.00601984,
        0.        ]])

# RF-GAP Rocket

In [8]:
from RFGAP_Rocket.RFGAP_Rocket import RFGAP_Rocket

rf_rocket = RFGAP_Rocket(prediction_type = "classification", rocket = "Multi",
                         n_kernels=512) # Rocket Kwargs
data_to_proximities(rf_rocket, XTRAIN, YTRAIN, XTEST, XSTATIC , XSTATIC_TEST)

array([[0.        , 0.05739166, 0.        , ..., 0.04784293, 0.015625  ,
        0.03977806],
       [0.04117928, 0.        , 0.00237374, ..., 0.02857564, 0.0121599 ,
        0.02422949],
       [0.01775778, 0.01226156, 0.        , ..., 0.0131712 , 0.04022902,
        0.01551812],
       ...,
       [0.04301686, 0.0269958 , 0.01111938, ..., 0.        , 0.02876984,
        0.03062926],
       [0.01370069, 0.00426274, 0.02751035, ..., 0.01162035, 0.        ,
        0.01100002],
       [0.03559571, 0.03878792, 0.        , ..., 0.03858105, 0.        ,
        0.        ]])

# RDST 

In [9]:
from RDST.rdst import RDST_GAP

rdst = RDST_GAP(save_transformed_data = True)
prox = data_to_proximities(rdst, XTRAIN, YTRAIN, None, XSTATIC , None)
prox

array([[0.        , 0.05196341, 0.        , ..., 0.03931727, 0.        ,
        0.02718149],
       [0.03645054, 0.        , 0.        , ..., 0.03870932, 0.        ,
        0.02274232],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04840185,
        0.        ],
       ...,
       [0.06200807, 0.03775314, 0.        , ..., 0.        , 0.        ,
        0.02966812],
       [0.        , 0.        , 0.06093975, ..., 0.        , 0.        ,
        0.        ],
       [0.0367239 , 0.03193232, 0.        , ..., 0.0410838 , 0.        ,
        0.        ]])

# PF GAP

In [14]:
sys.path.insert(0, '/yunity/arusty/PF-GAP/PFGAP')
from PFGAP.PyPFGAP import PyPFGAP
pf = PyPFGAP()
data_to_proximities(pf, XTRAIN, YTRAIN, None, XSTATIC , None)

reading file [train]:finished in 0:0:0.021
reading file [test]:finished in 0:0:0.009
Running on configurations...
Dataset: train, Training Data : 50x150 , Testing Data: 50x150, Train #Classes: 2, Test #Classes: 2
Repeats: 1 , Trees: 18 , Candidates per Split(r): 5
Output Dir: output, Export: 1, Verbosity: 1
Select DM per node: true , Shuffle Data: false, JVM WarmUp: false
----------------------------------------------------------------------------------------------------

-----------------Repetition No: 1 (train)   -----------------
Using: 4 MB, Free: 20 MB, Allocated Pool: 24 MB, Max Available: 1024 MB
core.ProximityForestResult@4f3f5b24
0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.
Using: 43 MB, Free: 41 MB, Allocated Pool: 84 MB, Max Available: 1024 MB
*
Computing Forest Proximities...
Done Computing Forest Proximities. Computation time: 16.0ms
Training Time: 2077.516929ms (0:0:2.077)
Prediction Time: 386.037957ms (0:0:0.386)
Correct(TP+TN): 50 vs Incorrect(FP+FN): 0
Accuracy: 1.0
Er

array([[0.        , 0.        , 0.3       , ..., 0.        , 0.05      ,
        0.        ],
       [0.1244203 , 0.        , 0.        , ..., 0.01606335, 0.        ,
        0.        ],
       [0.04738562, 0.        , 0.        , ..., 0.00980392, 0.12698413,
        0.        ],
       ...,
       [0.0764652 , 0.00595238, 0.1375    , ..., 0.        , 0.03125   ,
        0.        ],
       [0.        , 0.        , 0.28472222, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Fresh Prince

In [4]:
from FreshPrince.FreshPrince import FreshPRINCE_GAP

fp = FreshPRINCE_GAP()
prox = data_to_proximities(fp, XTRAIN, YTRAIN, None, XSTATIC , None)
prox

array([[0.        , 0.03508487, 0.        , ..., 0.03271543, 0.        ,
        0.04025505],
       [0.03791568, 0.        , 0.        , ..., 0.04208253, 0.        ,
        0.0338675 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0693021 ,
        0.        ],
       ...,
       [0.03857972, 0.04319684, 0.        , ..., 0.        , 0.        ,
        0.02920624],
       [0.        , 0.        , 0.04794557, ..., 0.        , 0.        ,
        0.        ],
       [0.04910631, 0.03447911, 0.        , ..., 0.02395265, 0.        ,
        0.        ]])

# Distance Measures
- These don't use static variables

In [4]:
from independent_distance.distance_helpers import compute_distance_matrix
compute_distance_matrix(XTRAIN, metric="dtw")

/yunity/arusty/PF-GAP/.venv/lib/python3.12/site-packages/tslearn/bases/bases.py:15: UserWarning: h5py not installed, hdf5 features will not be supported.
Install h5py to use hdf5 features: http://docs.h5py.org/
  warn(h5py_msg)


array([[ 0.        ,  4.62126067,  4.84338668, ...,  5.19192617,
         8.12897137, 12.07692907],
       [ 4.62126067,  0.        ,  2.49058685, ...,  2.77968935,
         4.19359482, 12.15547782],
       [ 4.84338668,  2.49058685,  0.        , ...,  2.85456547,
         4.11050844, 11.19458226],
       ...,
       [ 5.19192617,  2.77968935,  2.85456547, ...,  0.        ,
         4.84733788, 12.29014883],
       [ 8.12897137,  4.19359482,  4.11050844, ...,  4.84733788,
         0.        , 11.75686358],
       [12.07692907, 12.15547782, 11.19458226, ..., 12.29014883,
        11.75686358,  0.        ]])