# Testing each method works for the Pipeline 

In [1]:
from functions import *
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# QUANT

In [3]:
from QGAP.Quant_Static import StaticQuantClassifier as SQC
sqc = SQC()

In [4]:
data_to_proximities(sqc, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[ 9,  8, 10, ...,  6,  4,  2],
       [ 9,  8, 10, ...,  6,  4,  2],
       [ 6,  5,  1, ...,  4,  5,  8],
       ...,
       [ 9,  8, 10, ...,  6,  4,  7],
       [ 6,  5,  1, ...,  8,  5,  6],
       [11,  8, 10, ...,  9,  6,  4]])

# RF-GAP QUANT

In [5]:
from QGAP.qgap import QGAP
qgap = QGAP(matrix_type="dense")

In [6]:
data_to_proximities(qgap, XTRAIN, YTRAIN, XTEST, XSTATIC,XSTATIC_TEST)

array([[0.        , 0.04703672, 0.        , ..., 0.04620979, 0.        ,
        0.03049933],
       [0.04056226, 0.        , 0.        , ..., 0.06072211, 0.        ,
        0.02458607],
       [0.        , 0.        , 0.        , ..., 0.        , 0.10201168,
        0.        ],
       ...,
       [0.0566615 , 0.04622642, 0.        , ..., 0.        , 0.        ,
        0.02188681],
       [0.        , 0.        , 0.08932881, ..., 0.        , 0.        ,
        0.        ],
       [0.02735012, 0.01579963, 0.        , ..., 0.01645771, 0.        ,
        0.        ]])

# REDCOMMET

In [7]:
from Redcomets.Redcomets import REDCOMETS
redcomets = REDCOMETS(variant = 3, static = XSTATIC)
data_to_proximities(redcomets, XTRAIN, YTRAIN, XTEST, None , None)

array([[1.        , 0.41118901, 0.14750829, ..., 0.29097426, 0.12425707,
        0.22564188],
       [0.41118901, 1.        , 0.16298121, ..., 0.44697616, 0.1466493 ,
        0.23772146],
       [0.14750829, 0.16298121, 1.        , ..., 0.17380704, 0.40472446,
        0.06385283],
       ...,
       [0.29097426, 0.44697616, 0.17380704, ..., 1.        , 0.1480199 ,
        0.21672035],
       [0.12425707, 0.1466493 , 0.40472446, ..., 0.1480199 , 1.        ,
        0.09002526],
       [0.22564188, 0.23772146, 0.06385283, ..., 0.21672035, 0.09002526,
        1.        ]])