# Testing PyPFGAP

In [ ]:
from aeon.classification.shapelet_based import RDSTClassifier
import numpy as np
import os

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

from PFGAP.PyPFGAP import PyPFGAP


In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)

In [3]:
# Read the data from the TSV file
test_data_path = '/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TEST.tsv'
test_data = np.loadtxt(test_data_path, delimiter='\t')

# Display the shape of the loaded data
print("Shape of the test data:", test_data.shape)

Shape of the test data: (150, 151)


In [4]:
test_data[:, 0]

array([1., 2., 2., 1., 1., 2., 1., 2., 2., 1., 1., 1., 2., 1., 1., 1., 1.,
       2., 2., 2., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 2., 2., 1.,
       1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2., 1., 2., 2., 1., 2., 2.,
       2., 1., 2., 1., 1., 2., 2., 1., 2., 1., 2., 1., 1., 2., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 1., 1., 2., 2., 2.,
       2., 1., 2., 1., 1., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 2., 1.,
       1., 2., 2., 1., 1., 2., 1., 2., 2., 2., 1., 2., 1., 1., 2., 1., 1.,
       2., 1., 2., 2., 2., 1., 2., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2.,
       1., 2., 1., 1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 1.])

In [5]:
YTEST

array(['1', '2', '2', '1', '1', '2', '1', '2', '2', '1', '1', '1', '2',
       '1', '1', '1', '1', '2', '2', '2', '1', '2', '1', '1', '1', '2',
       '1', '1', '2', '1', '1', '2', '2', '1', '1', '1', '1', '1', '1',
       '2', '1', '2', '1', '1', '2', '1', '2', '2', '1', '2', '2', '2',
       '1', '2', '1', '1', '2', '2', '1', '2', '1', '2', '1', '1', '2',
       '1', '1', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
       '2', '1', '1', '1', '2', '2', '2', '2', '1', '2', '1', '1', '1',
       '2', '1', '2', '1', '1', '2', '2', '1', '1', '2', '1', '1', '2',
       '2', '1', '1', '2', '1', '2', '2', '2', '1', '2', '1', '1', '2',
       '1', '1', '2', '1', '2', '2', '2', '1', '2', '1', '1', '2', '2',
       '2', '2', '1', '1', '1', '2', '1', '2', '1', '1', '2', '1', '1',
       '2', '1', '2', '1', '2', '2', '1'], dtype='<U1')

In [6]:
pf = PyPFGAP()

In [7]:
train_data_path = '/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TRAIN.tsv'
train_data = np.loadtxt(train_data_path, delimiter='\t')
print("Shape of the training data:", train_data.shape)


Shape of the training data: (50, 151)


In [8]:
train_data[:, 2]

array([-0.64199155, -0.64540093, -0.77827907, -0.7481029 , -0.59742191,
       -0.55366008, -1.294884  , -2.0120689 , -1.0665005 , -1.1758389 ,
       -0.81410425, -1.1407461 , -1.186591  , -1.2084099 , -0.60737568,
       -1.161359  , -0.80929234, -0.61916421, -1.0507165 , -1.0824705 ,
       -0.849687  , -0.7728034 , -1.1867783 , -1.7464956 , -0.71306248,
       -0.97210768, -1.012182  , -1.0788593 , -1.008827  , -1.5047556 ,
       -0.96426418, -1.4829241 , -0.97910197, -0.72526276, -0.64100512,
       -0.60808394, -1.2824317 , -0.54858405, -1.6236964 , -1.1131568 ,
       -0.73426195, -1.1508991 , -0.97268011, -1.2430027 , -1.0374974 ,
       -0.56504961, -0.61498675, -0.77837863, -0.70261754, -1.4322717 ])

In [9]:
XTRAIN.shape

(50, 1, 150)

In [12]:
# Run the Java process with reshaped XTRAIN
pf.run_Java(XTRAIN, YTRAIN, XTEST, YTEST, static=XSTATIC)

reading file [train]:finished in 0:0:0.020
reading file [test]:finished in 0:0:0.023
Running on configurations...
Dataset: train, Training Data : 50x150 , Testing Data: 150x150, Train #Classes: 2, Test #Classes: 2
Repeats: 1 , Trees: 18 , Candidates per Split(r): 5
Output Dir: output, Export: 1, Verbosity: 1
Select DM per node: true , Shuffle Data: false, JVM WarmUp: false
----------------------------------------------------------------------------------------------------

-----------------Repetition No: 1 (train)   -----------------
Using: 4 MB, Free: 30 MB, Allocated Pool: 34 MB, Max Available: 1024 MB
core.ProximityForestResult@4f3f5b24
0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.
Using: 52 MB, Free: 38 MB, Allocated Pool: 90 MB, Max Available: 1024 MB
**
Computing Forest Proximities...
Done Computing Forest Proximities. Computation time: 18.0ms
Training Time: 1951.598710ms (0:0:1.951)
Prediction Time: 1138.013321ms (0:0:1.138)
Correct(TP+TN): 149 vs Incorrect(FP+FN): 1
Accuracy: 0.

array([[0.        , 0.        , 0.        , ..., 0.03367003, 0.13333333,
        0.        ],
       [0.06200397, 0.        , 0.        , ..., 0.0973575 , 0.        ,
        0.02128623],
       [0.        , 0.        , 0.        , ..., 0.        , 0.25698006,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.2       ,
        0.04166667],
       [0.05555556, 0.        , 0.375     , ..., 0.11111111, 0.        ,
        0.        ],
       [0.02857143, 0.00952381, 0.        , ..., 0.03722944, 0.        ,
        0.        ]])

In [11]:
#Verification Tests
from PFGAP.Application.proxUtil import getProx, getProxArrays
mytrain = "/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TRAIN.tsv"
mytest = "/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TEST.tsv"
getProx(mytrain, mytest, num_trees=18, r=5)
prox,labels = getProxArrays()
print(prox)

reading file [GunPoint_TRAIN.tsv]:finished in 0:0:0.022
reading file [GunPoint_TEST.tsv]:finished in 0:0:0.019
Running on configurations...
Dataset: GunPoint_TRAIN.tsv, Training Data : 50x150 , Testing Data: 150x150, Train #Classes: 2, Test #Classes: 2
Repeats: 1 , Trees: 18 , Candidates per Split(r): 5
Output Dir: output, Export: 1, Verbosity: 1
Select DM per node: true , Shuffle Data: false, JVM WarmUp: false
----------------------------------------------------------------------------------------------------

-----------------Repetition No: 1 (GunPoint_TRAIN.tsv)   -----------------
Using: 4 MB, Free: 30 MB, Allocated Pool: 34 MB, Max Available: 1024 MB
core.ProximityForestResult@4f3f5b24
0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.
Using: 48 MB, Free: 42 MB, Allocated Pool: 90 MB, Max Available: 1024 MB
**
Computing Forest Proximities...
Done Computing Forest Proximities. Computation time: 17.0ms
Training Time: 1936.832782ms (0:0:1.936)
Prediction Time: 996.703784ms (0:0:0.996)
Corr