# Testing PyPFGAP

In [1]:
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

from PFGAP.PyPFGAP import PyPFGAP


In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)

In [3]:
# Read the data from the TSV file
test_data_path = '/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TEST.tsv'
test_data = np.loadtxt(test_data_path, delimiter='\t')

# Display the shape of the loaded data
print("Shape of the test data:", test_data.shape)

Shape of the test data: (150, 151)


In [4]:
test_data[:, 0]

array([1., 2., 2., 1., 1., 2., 1., 2., 2., 1., 1., 1., 2., 1., 1., 1., 1.,
       2., 2., 2., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 2., 2., 1.,
       1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2., 1., 2., 2., 1., 2., 2.,
       2., 1., 2., 1., 1., 2., 2., 1., 2., 1., 2., 1., 1., 2., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 1., 1., 2., 2., 2.,
       2., 1., 2., 1., 1., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 2., 1.,
       1., 2., 2., 1., 1., 2., 1., 2., 2., 2., 1., 2., 1., 1., 2., 1., 1.,
       2., 1., 2., 2., 2., 1., 2., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2.,
       1., 2., 1., 1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 1.])

In [5]:
YTEST

array(['1', '2', '2', '1', '1', '2', '1', '2', '2', '1', '1', '1', '2',
       '1', '1', '1', '1', '2', '2', '2', '1', '2', '1', '1', '1', '2',
       '1', '1', '2', '1', '1', '2', '2', '1', '1', '1', '1', '1', '1',
       '2', '1', '2', '1', '1', '2', '1', '2', '2', '1', '2', '2', '2',
       '1', '2', '1', '1', '2', '2', '1', '2', '1', '2', '1', '1', '2',
       '1', '1', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
       '2', '1', '1', '1', '2', '2', '2', '2', '1', '2', '1', '1', '1',
       '2', '1', '2', '1', '1', '2', '2', '1', '1', '2', '1', '1', '2',
       '2', '1', '1', '2', '1', '2', '2', '2', '1', '2', '1', '1', '2',
       '1', '1', '2', '1', '2', '2', '2', '1', '2', '1', '1', '2', '2',
       '2', '2', '1', '1', '1', '2', '1', '2', '1', '1', '2', '1', '1',
       '2', '1', '2', '1', '2', '2', '1'], dtype='<U1')

In [6]:
pf = PyPFGAP()

In [7]:
train_data_path = '/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TRAIN.tsv'
train_data = np.loadtxt(train_data_path, delimiter='\t')
print("Shape of the training data:", train_data.shape)


Shape of the training data: (50, 151)


In [8]:
train_data[:, 2]

array([-0.64199155, -0.64540093, -0.77827907, -0.7481029 , -0.59742191,
       -0.55366008, -1.294884  , -2.0120689 , -1.0665005 , -1.1758389 ,
       -0.81410425, -1.1407461 , -1.186591  , -1.2084099 , -0.60737568,
       -1.161359  , -0.80929234, -0.61916421, -1.0507165 , -1.0824705 ,
       -0.849687  , -0.7728034 , -1.1867783 , -1.7464956 , -0.71306248,
       -0.97210768, -1.012182  , -1.0788593 , -1.008827  , -1.5047556 ,
       -0.96426418, -1.4829241 , -0.97910197, -0.72526276, -0.64100512,
       -0.60808394, -1.2824317 , -0.54858405, -1.6236964 , -1.1131568 ,
       -0.73426195, -1.1508991 , -0.97268011, -1.2430027 , -1.0374974 ,
       -0.56504961, -0.61498675, -0.77837863, -0.70261754, -1.4322717 ])

In [9]:
XTRAIN.shape

(50, 1, 150)

In [10]:
# Run the Java process with reshaped XTRAIN
pf.fit(XTRAIN, YTRAIN, static=XSTATIC)

reading file [train]:finished in 0:0:0.020
reading file [test]:finished in 0:0:0.009
Running on configurations...
Dataset: train, Training Data : 50x150 , Testing Data: 50x150, Train #Classes: 2, Test #Classes: 2
Repeats: 1 , Trees: 18 , Candidates per Split(r): 5
Output Dir: output, Export: 1, Verbosity: 1
Select DM per node: true , Shuffle Data: false, JVM WarmUp: false
----------------------------------------------------------------------------------------------------

-----------------Repetition No: 1 (train)   -----------------
Using: 4 MB, Free: 23 MB, Allocated Pool: 27 MB, Max Available: 1024 MB
core.ProximityForestResult@4f3f5b24
0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.
Using: 53 MB, Free: 32 MB, Allocated Pool: 85 MB, Max Available: 1024 MB
*
Computing Forest Proximities...
Done Computing Forest Proximities. Computation time: 15.0ms
Training Time: 1963.245786ms (0:0:1.963)
Prediction Time: 341.447618ms (0:0:0.341)
Correct(TP+TN): 50 vs Incorrect(FP+FN): 0
Accuracy: 1.0
Er

array([[0.        , 0.06439037, 0.        , ..., 0.10900647, 0.        ,
        0.00595238],
       [0.03703704, 0.        , 0.        , ..., 0.05113636, 0.        ,
        0.00694444],
       [0.02834467, 0.03139717, 0.        , ..., 0.04238619, 0.02527473,
        0.        ],
       ...,
       [0.19111111, 0.04666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.04613095, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01785714, 0.        , ..., 0.00595238, 0.        ,
        0.        ]])

In [11]:
#Verification Tests
from PFGAP.Application.proxUtil import getProx, getProxArrays
mytrain = "/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TRAIN.tsv"
mytest = "/yunity/arusty/PF-GAP/PFGAP/PFGAP/Data/GunPoint_TEST.tsv"
getProx(mytrain, mytest, num_trees=18, r=5)
prox,labels = getProxArrays()
print(prox)

reading file [GunPoint_TRAIN.tsv]:finished in 0:0:0.021
reading file [GunPoint_TEST.tsv]:finished in 0:0:0.018
Running on configurations...
Dataset: GunPoint_TRAIN.tsv, Training Data : 50x150 , Testing Data: 150x150, Train #Classes: 2, Test #Classes: 2
Repeats: 1 , Trees: 18 , Candidates per Split(r): 5
Output Dir: output, Export: 1, Verbosity: 1
Select DM per node: true , Shuffle Data: false, JVM WarmUp: false
----------------------------------------------------------------------------------------------------

-----------------Repetition No: 1 (GunPoint_TRAIN.tsv)   -----------------
Using: 4 MB, Free: 30 MB, Allocated Pool: 34 MB, Max Available: 1024 MB
core.ProximityForestResult@4f3f5b24
0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.
Using: 41 MB, Free: 49 MB, Allocated Pool: 90 MB, Max Available: 1024 MB
**
Computing Forest Proximities...
Done Computing Forest Proximities. Computation time: 14.0ms
Training Time: 1962.608210ms (0:0:1.962)
Prediction Time: 1120.886152ms (0:0:1.120)
Cor