# Import data and libraries

In [13]:
from rfgap import RFGAP
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [14]:
# Load Data
# XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
# XTEST, YTEST = load_gunpoint(split="TEST")

XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# Basic Model Tests 
To ensure they are loaded correctly

## Testing RF_GAP seperately

In [15]:
prediction_type = 'classification'

rf = RFGAP(prediction_type = prediction_type)
rf.fit(np.random.rand(5, 5), np.random.randint(0, 2, size=(5,)))

print(rf.get_proximities().todense())

[[0.         0.20055556 0.23277778 0.26111111 0.30555556]
 [0.31954023 0.         0.37011494 0.1091954  0.20114943]
 [0.41236559 0.42634409 0.         0.04032258 0.12096774]
 [0.22587719 0.20438596 0.20131579 0.         0.36842105]
 [0.24305556 0.26666667 0.18472222 0.30555556 0.        ]]


## Testing the Rockets
Safety first, right?

In [16]:
from aeon.transformations.collection.convolution_based import MultiRocket, MiniRocket
from aeon.datasets import load_unit_test
X_train, y_train = load_unit_test(split="train")
X_test, y_test = load_unit_test(split="test")
rocket = MultiRocket(n_kernels=512)
rocket.fit(X_train)

X_train = rocket.transform(X_train)
X_test = rocket.transform(X_test)

# RFGAP ROCKET

In [17]:
from RFGAP_Rocket import RFGAP_Rocket

#NOT STATIC 
rf_rocket = RFGAP_Rocket(prediction_type = prediction_type, rocket = "Multi",
                         n_kernels=512) # Rocket Kwargs
rf_rocket.fit(XTRAIN, YTRAIN)
prox = rf_rocket.get_proximities().todense()

print(f"Proximities shape {prox.shape}")
print(f"Data shape {XTRAIN.shape}")
print(f"Proximities: \n{prox}")

Proximities shape (40, 40)
Data shape (40, 6, 100)
Proximities: 
[[0.         0.084874   0.08193582 ... 0.         0.         0.        ]
 [0.09573513 0.         0.07273228 ... 0.00347222 0.         0.        ]
 [0.07846472 0.09588141 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.10456237 0.09106297]
 [0.00816993 0.0130719  0.00294118 ... 0.07389718 0.         0.0631376 ]
 [0.         0.         0.         ... 0.12949905 0.09392358 0.        ]]


In [18]:
from RFGAP_Rocket import RFGAP_Rocket

rf_rocket = RFGAP_Rocket(prediction_type = prediction_type, rocket = "Multi",
                         n_kernels=512) # Rocket Kwargs
rf_rocket.fit(XTRAIN, YTRAIN, XSTATIC)
prox_static = rf_rocket.get_proximities().todense()

print(f"Proximities shape {prox.shape}")
print(f"Data shape {XTRAIN.shape}")
print(f"Proximities: \n{prox}")

Proximities shape (40, 40)
Data shape (40, 6, 100)
Proximities: 
[[0.         0.084874   0.08193582 ... 0.         0.         0.        ]
 [0.09573513 0.         0.07273228 ... 0.00347222 0.         0.        ]
 [0.07846472 0.09588141 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.10456237 0.09106297]
 [0.00816993 0.0130719  0.00294118 ... 0.07389718 0.         0.0631376 ]
 [0.         0.         0.         ... 0.12949905 0.09392358 0.        ]]


In [19]:
prox_static == prox

matrix([[ True, False, False, ...,  True,  True,  True],
        [False,  True, False, ..., False,  True, False],
        [False, False,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True, False, False],
        [False, False, False, ..., False,  True, False],
        [ True,  True,  True, ..., False, False,  True]])