# Import data and libraries

In [1]:
from rfgap import RFGAP
import numpy as np

#Data
from aeon.datasets import load_gunpoint
from aeon.datasets import load_basic_motions

#Adjust the path
import sys
sys.path.insert(0, '/yunity/arusty/PF-GAP')

In [2]:
# Load Data
XTRAIN, YTRAIN = load_gunpoint(split="TRAIN")
XTEST, YTEST = load_gunpoint(split="TEST")

# XTRAIN, YTRAIN = load_basic_motions(split="TRAIN")
# XTEST, YTEST = load_basic_motions(split="TEST")

#Generate random static variables to test algorithm
XSTATIC = np.random.rand(XTRAIN.shape[0], 45)
XSTATIC_TEST = np.random.rand(XTEST.shape[0], 45)


# Basic Model Tests 
To ensure they are loaded correctly

## Testing RF_GAP seperately

In [3]:
prediction_type = 'classification'

rf = RFGAP(prediction_type = prediction_type)
rf.fit(np.random.rand(5, 5), np.random.randint(0, 2, size=(5,)))

print(rf.get_proximities().todense())

[[0.         0.40215054 0.03494624 0.40430108 0.15860215]
 [0.31666667 0.         0.1412037  0.46111111 0.08101852]
 [0.25121951 0.34349593 0.         0.25894309 0.14634146]
 [0.24646465 0.42020202 0.20959596 0.         0.12373737]
 [0.2042735  0.22222222 0.35897436 0.21452991 0.        ]]


## Testing the Rockets
Safety first, right?

In [ ]:
from aeon.transformations.collection.convolution_based import MultiRocket, MiniRocket
from aeon.datasets import load_unit_test
X_train, y_train = load_unit_test(split="train")
X_test, y_test = load_unit_test(split="test")
rocket = MultiRocket(n_kernels=512)
rocket.fit(X_train)

X_train = rocket.transform(X_train)
X_test = rocket.transform(X_test)

# RFGAP ROCKET